apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oofbs4fxq-nodejs 
  janus-idp.io/tekton: oofbs4fxq-nodejs
  backstage.io/kubernetes-id: oofbs4fxq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oofbs4fxq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml