apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oofbs4fxq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oofbs4fxq-nodejs 
  name: oofbs4fxq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oofbs4fxq-nodejs 
